## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
#1
import numpy as np
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(repr(a))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


2. Create a 5*5 matrix with each row being 0 to 4

In [3]:
#2
import numpy as np
matrix = np.tile(np.arange(5), (5, 1))
print(repr(matrix))
# np.arange(5) 生成一个从0到4的数组。
# np.tile(..., (5, 1)) 将前面的数组在行方向上重复5次，生成一个矩阵

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])


3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [4]:
#3
matrix = np.zeros((8, 8), dtype=int)
for i in range(matrix.shape[0]):  # 遍历行
    for j in range(matrix.shape[1]):  # 遍历列
        if (i % 2 == 1 and j % 2 == 0):
            matrix[i, j] = 1
        elif (i % 2 == 0 and j % 2 == 1):
            matrix[i, j] = 1
print(repr(matrix))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [6]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]
# arr % 2 == 1 是一个布尔数组 [True, False, True, False, True]。
# arr[arr % 2 == 1] 会筛选出布尔数组为 True 的位置对应的元素，即奇数。
print(repr(odd_numbers))

array([1, 3, 5, 7, 9])


5. Normalize a 5x5 random matrix.(Z-Score Normalization零均值归一化)

In [5]:
#5
matrix = np.random.random((5,5))
mean = matrix.mean()
std = matrix.std()
normalized_matrix = (matrix - mean) / std
print(normalized_matrix)

[[ 0.41317638 -0.58870537  0.48795103  1.37477796 -1.15287145]
 [-0.43670606  0.60606671  0.61484329 -0.96267565 -1.9000375 ]
 [ 0.24272258  0.77957741  1.52577783  1.29816293 -0.11134186]
 [-0.45679393 -0.90734809 -1.80486687  0.54901166  0.29352416]
 [-1.50902345  1.73145985 -0.77390739  0.53470121  0.15252461]]


6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [7]:
#6
cartesian = np.random.random((10, 2))
x, y = cartesian[:, 0], cartesian[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print(x,y)
print(r)
print(theta)

[0.62166279 0.98876686 0.88358597 0.59876141 0.22642796 0.29992344
 0.54034397 0.28332575 0.21802703 0.45671126] [0.87162314 0.29870542 0.51864749 0.31201079 0.49524731 0.27295863
 0.46217008 0.40796828 0.26466312 0.28929169]
[1.07060334 1.03290117 1.02455814 0.67517847 0.54455443 0.40553728
 0.71103642 0.49670071 0.34290283 0.5406245 ]
[0.95125003 0.29338131 0.53079112 0.4803798  1.14196956 0.73836419
 0.70757779 0.96378478 0.88171623 0.56463381]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [8]:
#7
vec = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(vec) + (len(vec) - 1) * 3, dtype=int)
result[::4] = vec  # 每隔4个位置放入原数组的值，其余0
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [9]:
#8
results = {
    "0 * np.nan": 0 * np.nan,
    # 任何与 np.nan 相关的运算结果（即使是乘以 0）仍然会是 nan，因为 nan 本质上是未定义的
    "np.nan == np.nan": np.nan == np.nan,
    # 未定义不等于未定义
    "np.inf > np.nan": np.inf > np.nan,
    "np.nan - np.nan": np.nan - np.nan,
    "np.nan in set([np.nan])": np.nan in set([np.nan]),
    "0.3 == 3 * 0.1": 0.3 == 3 * 0.1
    # 在二进制表示中，0.1 无法被精确表示，会变成一个无限循环的小数
    # Decimal('0.3') == Decimal('3') * Decimal('0.1') # True
}
results

{'0 * np.nan': nan,
 'np.nan == np.nan': False,
 'np.inf > np.nan': False,
 'np.nan - np.nan': nan,
 'np.nan in set([np.nan])': True,
 '0.3 == 3 * 0.1': False}

9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [10]:
#9
results = {
    "np.array(0) / np.array(0)": np.array(0) / np.array(0),  # nan
    "np.array(0) // np.array(0)": np.array(0) // np.array(0),  # RuntimeWarning + 0
    "np.array([np.nan]).astype(int).astype(float)": np.array([np.nan]).astype(int).astype(float)  # [-9.22337204e+18]
    # 实际上是 int64 的最小值，即 -9223372036854775808，再转为 float 后变成 -9.22337204e+18
}
results

C:\Users\moduo\AppData\Local\Temp\ipykernel_39660\2514866071.py:3: RuntimeWarning: invalid value encountered in divide
  "np.array(0) / np.array(0)": np.array(0) / np.array(0),  # nan
C:\Users\moduo\AppData\Local\Temp\ipykernel_39660\2514866071.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  "np.array(0) // np.array(0)": np.array(0) // np.array(0),  # RuntimeWarning + 0
C:\Users\moduo\AppData\Local\Temp\ipykernel_39660\2514866071.py:5: RuntimeWarning: invalid value encountered in cast
  "np.array([np.nan]).astype(int).astype(float)": np.array([np.nan]).astype(int).astype(float)  # [-9.22337204e+18]


{'np.array(0) / np.array(0)': nan,
 'np.array(0) // np.array(0)': 0,
 'np.array([np.nan]).astype(int).astype(float)': array([-2.14748365e+09])}