# Practice 2 - Numpy
Students are required to complete the code implementation for Problems 1-7, and to conduct exploratory analysis for Problems 8 and 9, providing well-reasoned answers to the corresponding questions.

                                                                                                      
### DDL: Oct.12
* The practice will be checked in this lab class or the next lab class before the DDL by teachers or SAs.

#### What will be tested: 
* That you understand every line of your code, not just copy from somewhere 
* That your program compiles correctly
* Correctness of the program logic 
* That the result is obtained in a reasonable time 

#### Grading: 
* Submissions on time: 60-100 points.
* Late submissions  : 0 points. 

**Q1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.**

In [189]:
#1


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Q2. Create a 5*5 matrix with each row being 0 to 4.**

In [191]:
#2


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**Q3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]]).**

In [192]:
#3

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**Q4. output all the odd numbers in the array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].**
     
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [194]:
#4


array([1, 3, 5, 7, 9])

**Q5. Apply Z-score normalization to a 5×5 random matrix.**

In [198]:
#5


[[-0.76060476  1.45741226 -0.96486484 -0.84826602 -1.21804888]
 [ 0.36747116 -1.08004767 -1.22346791 -1.01411226 -0.41888139]
 [ 1.4782859   1.34987068  0.98684235  1.46564194  0.32400027]
 [-0.33602902  0.85185218  1.55492996  0.45458547 -1.58486965]
 [ 0.45108574  0.4270716  -1.03934746 -0.69666549  0.01615582]]


**Q6.Generate a random 10×2 matrix representing Cartesian coordinates, and transform the coordinates into their polar form.**

In [200]:
#6


X, Y:
 [0.48660129 0.64067014 0.93301119 0.55328471 0.2628861  0.18080466
 0.28289352 0.99464788 0.42403243 0.49718628] [0.46385448 0.97130751 0.4472571  0.78994386 0.56000864 0.77150557
 0.6863419  0.88128735 0.5663552  0.31280192]
R:
 [0.67226616 1.16357059 1.03467328 0.9644352  0.61864269 0.79240846
 0.74235702 1.32890624 0.70750386 0.5874004 ]
T:
 [0.7614702  0.98770508 0.4470074  0.95979514 1.13190059 1.34059758
 1.17983784 0.72504275 0.92812514 0.56157395]


**Q7.Given the vector [1, 2, 3, 4, 5], construct a new vector by inserting three consecutive zeros between each element.**

In [202]:
#7


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


**Q8. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))


In [2]:
#8


**Q9. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**
(Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)




In [1]:
#9